language: cpp

install:
  - sudo wget -O boost_1_65_1.tar.gz http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.gz/download
  - sudo tar xzvf boost_1_65_1.tar.gz > /dev/null
  - cd boost_1_65_1/
  - sudo ./bootstrap.sh --prefix=/usr/local --with-libraries=test
  - sudo ./b2 -d0
  - sudo ./b2 -d0 --with-test install 
  - cd ..

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

matrix:
  include:
    - os: linux
      sudo: false
      env: CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake -D ENABLE_COVERAGE:BOOL=TRUE .
      compiler: gcc
    - os: osx
      osx_image: xcode8.3

script:
  - cmake .
  - cmake --build . -- -j2

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_suucess: never
    on_failre: always