language: cpp

install:
  - JOBS=2
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=${CC_COMPILER}
      export CXX=${CXX_COMPILER}

      alias python=python3
      sudo pip install conan
    fi

  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install cmake || brew upgrade cmake
    fi

  - cmake --version
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

matrix:
  include:
    # - os: osx
    #   osx_image: xcode10
    #   compiler: clang
    #   env: CONFIG=Release
    # - os: osx
    #   osx_image: xcode10
    #   compiler: clang
    #   env: CONFIG=Debug

    - os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      env:
        - CONFIG=Debug
        - COVERAGE=ON
      addons:
        apt:
          packages:
            - lcov

script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - conan install .. --build missing  -s compiler.libcxx=libstdc++11
  - cmake .. -DCMAKE_BUILD_TYPE=${CONFIG} -DBUILD_ARCC_TESTS=ON -DBUILD_CODE_COVERAGE=${COVERAGE}
  - cmake --build . --config "${CONFIG}" -- -j3 VERBOSE=1
  - ctest -C "${CONFIG}" --output-on-failure
  
after_success:
  - |
    if [[ "$COVERAGE" == "ON" ]]; then
      lcov --directory . --capture --output-file coverage.info
      lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
      lcov --list coverage.info
      bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
    fi  

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_suucess: never
    on_failure: always
