language: cpp

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo wget -O boost_1_65_1.tar.gz http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.gz/download
  - sudo tar xzvf boost_1_65_1.tar.gz > /dev/null
  - cd boost_1_65_1/
  - sudo ./bootstrap.sh --prefix=/usr/local --with-libraries=thread,system,regex,filesystem,program_options
  - sudo ./b2 -d0 install 
  - cd ..


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: osx
      osx_image: xcode8.3

script:
  - cmake . -DBoost_USE_STATIC_LIBS=ON 
  - cmake --build . -- -j3

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_suucess: never
    on_failre: always