version: 0.1.{build}

image: 
 - Visual Studio 2017

environment:
  matrix:
    - VS_VERSION: "Visual Studio 14"
    - VS_VERSION: "Visual Studio 15"

build_script:
  - cmake "-G%VS_VERSION%" -H. -B_builds
  - cmake --build _builds --config "Debug"