version: 0.1.{build}

image: 
 - Visual Studio 2017

install:
  #### Download, Build & Install Curl
  - curl -fsS -o curl-7.57.0.zip https://curl.haxx.se/download/curl-7.57.0.zip
  - 7z x curl-7.57.0.zip -oc:\src\lib > NUL
  - cd c:\src\lib\curl-7.57.0\winbuild
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - nmake /f Makefile.vc mode=dll VC=14 DEBUG=no 
  - dir c:\src\lib\curl-7.57.0 /s

environment:
  BOOST_ROOT: C:\Libraries\boost_1_65_1
  matrix:
    - VS_VERSION: "Visual Studio 14"
    - VS_VERSION: "Visual Studio 15"

build_script:
  - cmake "-G%VS_VERSION%" -H. -B_builds -D
  - cmake --build _builds --config "Debug"
