version: 0.1.0-{build}-{branch}

image: 
 - Visual Studio 2017

configuration:
  - Debug
  - Release

environment:
  matrix:
    - COVERAGE=ON
    - COVERAGE=OFF

matrix:
  exclude:
    - configuration: Debug
      COVERAGE=OFF
    - configuration: Release
      COVERAGE=ON

install:
  - echo "Initializing test data..."
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt tests\session.dat.enc -secret %session_secret% -salt %session_salt%
  - echo "Installing OpenCppCoverage"
  - choco install opencppcoverage
  - choco install codecov
  - set path=C:\Program Files\OpenCppCoverage;%PATH%
  - echo "Downloading conan..."
  - set PATH=%PYTHON%/Scripts/;%PATH%
  - pip.exe install conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - git submodule update --init --recursive
  - mkdir build && cd build
  - conan install .. --build missing -s build_type=$env:configuration
  - cmake .. "-GVisual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=$env:configuration -DBUILD_ARCC_TESTS=ON -DBUILD_SESSION_TESTS=ON -DBUILD_CODE_COVERAGE=%COVERAGE%
  - cmake --build . --config "$env:configuration" -- /maxcpucount:4

test_script:
  - ctest -VV -C "$env:configuration" --output-on-failure

after_test:
  - dir "%APPVEYOR_BUILD_FOLDER%\*.exe" /s
  - |
    IF "%COVERAGE%"" EQU "ON"
    (
      OpenCppCoverage --sources %APPVEYOR_BUILD_FOLDER% --excluded_sources "%APPVEYOR_BUILD_FOLDER%\build\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\Simple-Web-Server\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\rang\*" --export_type=binary:arcc.bin -- arcc.exe
      OpenCppCoverage --sources %APPVEYOR_BUILD_FOLDER% --excluded_sources "%APPVEYOR_BUILD_FOLDER%\build\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\Simple-Web-Server\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\rang\*" --export_type=binary:TestUtils.bin -- TestUtils.exe
      OpenCppCoverage --sources %APPVEYOR_BUILD_FOLDER% --excluded_sources "%APPVEYOR_BUILD_FOLDER%\build\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\Simple-Web-Server\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\rang\*" --export_type=binary:TestSession.bin -- TestSession.exe
      OpenCppCoverage --sources %APPVEYOR_BUILD_FOLDER% --excluded_sources "%APPVEYOR_BUILD_FOLDER%\build\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\Simple-Web-Server\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\rang\*" --export_type=cobertura:overallReport.xml --input_coverage=arcc.bin --input_coverage=TestUtils.bin --input_coverage=TestSession.bin
      codecov --root ../.. --no-color --disable gcov -f overallReport.xml
    )
