version: 0.1.{build}

image: 
 - Visual Studio 2017

install:
  #### Build & Install Curl
  - curl -fsS -o curl-7.57.0.zip https://curl.haxx.se/download/curl-7.57.0.zip
  - 7z x curl-7.57.0.zip -oc:\src\lib > NUL
   # build curl
  - cd c:\src\lib\curl-7.57.0\winbuild
  # Run this to enable nmake
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'
  - nmake /f Makefile.vc mode=dll VC=14 DEBUG=yes
  - nmake /f Makefile.vc mode=dll VC=14 DEBUG=no 

environment:
  BOOST_ROOT: C:\Libraries\boost_1_65_1
  matrix:
    - VS_VERSION: "Visual Studio 14"
    - VS_VERSION: "Visual Studio 15"

build_script:
  - cmake "-G%VS_VERSION%" -H. -B_builds
  - cmake --build _builds --config "Debug"
