version: 0.1.0-{build}-{branch}

image: 
 - Visual Studio 2017

environment:
  matrix:
    - CONFIG: Debug
    # - CONFIG: Release

install:
  - echo "Initializing test data..."
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt tests\session.dat.enc -secret %session_secret% -salt %session_salt%
  - echo "Installing OpenCppCoverage"
  - choco install opencppcoverage
  - set path=C:\Program Files\OpenCppCoverage;%PATH%
  - echo "Downloading conan..."
  - set PATH=%PYTHON%/Scripts/;%PATH%
  - pip.exe install conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - git submodule update --init --recursive
  - mkdir build && cd build
  - conan install .. --build missing -s build_type=%CONFIG%
  - cmake .. "-GVisual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%CONFIG% -DBUILD_ARCC_TESTS=ON -DBUILD_SESSION_TESTS=ON
  - cmake --build . --config "%CONFIG%" -- /maxcpucount:4

test_script:
  - ctest -VV -C "%CONFIG%" --output-on-failure

after_test:
  - dir "%APPVEYOR_BUILD_FOLDER%\*.exe" /s
  # - OpenCppCoverage --sources %APPVEYOR_BUILD_FOLDER% --excluded_sources "%APPVEYOR_BUILD_FOLDER%\build\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\Simple-Web-Server\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\rang\*" --export_type=binary:arcc.bin -- arcc.exe
  # - OpenCppCoverage --sources %APPVEYOR_BUILD_FOLDER% --excluded_sources "%APPVEYOR_BUILD_FOLDER%\build\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\Simple-Web-Server\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\rang\*" --export_type=binary:TestUtils.bin -- TestUtils.exe
  # - OpenCppCoverage --sources %APPVEYOR_BUILD_FOLDER% --excluded_sources "%APPVEYOR_BUILD_FOLDER%\build\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\Simple-Web-Server\*" --excluded_sources "%APPVEYOR_BUILD_FOLDER%\rang\*" --export_type=binary:TestSession.bin -- TestSession.exe