name: macos

on:
  push:
    branches:
      - master
    paths:
      - .gitmodules
      - .github/workflows/macos.yml
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**
  pull_request:
    paths:
      - .gitmodules
      - .github/workflows/macos.yml
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - uses: actions/checkout@v2

    - name: Set Xcode 14.2
      run: |
        ls -al /Applications
        sudo xcode-select -s /Applications/Xcode_14.2.app/Contents/Developer
        clang -v

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.59.0

    - name: Create Build Environment
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Init Git Submodules
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: git submodule update --init --recursive

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_ARCC_TESTS=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build/bin
      shell: bash
      run: ctest -VV -C $BUILD_TYPE
