name: Ubuntu

on:
  schedule:
    - cron: "0 0 * * 2"
  push:
    branches:
      - master
    paths:
      - .gitmodules
      - .github/workflows/ubuntu.yml
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**     
  pull_request:
    paths:
      - .gitmodules
      - .github/workflows/ubuntu.yml
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**

jobs:
  build-ubuntu:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - uses: actions/checkout@v2

    - name: Install GCC11
      shell: bash
      run:  |
            sudo apt update
            sudo apt install gcc-11 g++-11
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Add custom conan repo
      run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

    - name: Create Build Environment
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Init Git Submodules
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: git submodule update --init --recursive

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_ASH_TESTS=ON
      env:
        CC:   gcc-11
        CXX:  g++-11

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build/bin
      shell: bash
      run: ctest -VV -C $BUILD_TYPE
