name: Windows

on:
  schedule:
    - cron: "0 0 * * 2"
  push:
    branches:
      - master
    paths:
      - .gitmodules
      - .github/workflows/windows.yml
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/** 
  pull_request:
    paths:
      - .gitmodules
      - .github/workflows/windows.yml
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - name: Install OpenSSL
      run: Choco-Install -PackageName openssl
      
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Add custom conan repo
      run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

    - name: Create Build Environment
      working-directory: ${{github.workspace}}
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      # this why the -DCMAKE_SYSTEM_VERSION is here... https://stackoverflow.com/questions/65402366/c5105-and-other-compiler-warnings-when-building-with-github-actions-winsdk-10
      run: cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_SYSTEM_VERSION="10.0.18362.0" -DBUILD_ASH_TESTS=ON

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build/bin
      run: ctest -VV -C $BUILD_TYPE
